import type { SensitiveActionConsumption } from "./decisions.ts";
import type { ProviderMergeRequest, ProviderMergeResult, GitHubMutationClient } from "./providers.github-mutation.ts";
import { executeProviderMerge } from "./providers.github-mutation.ts";
import { BitbucketProviderError } from "./providers.bitbucket.ts";

type Fetcher=(input:string|URL|Request,init?:RequestInit)=>Promise<Response>;
function parts(repositoryId:string){const value=repositoryId.split("/");if(value.length!==2||value.some(part=>!part))throw new BitbucketProviderError("invalid_request","Bitbucket repository identity must be workspace/repository.");return{workspace:encodeURIComponent(value[0]!),repo:encodeURIComponent(value[1]!)};}
function record(value:unknown,label:string):Record<string,unknown>{if(typeof value!=="object"||value===null||Array.isArray(value))throw new BitbucketProviderError("incomplete_evidence",`${label} is malformed.`);return value as Record<string,unknown>;}
function nested(value:Record<string,unknown>,...keys:string[]){let current=value;for(const key of keys)current=record(current[key],key);return current;}
function text(value:Record<string,unknown>,key:string){if(typeof value[key]!=="string"||value[key]==="")throw new BitbucketProviderError("incomplete_evidence",`${key} is missing.`);return value[key] as string;}
export class BitbucketMutationRestClient implements Pick<GitHubMutationClient,"merge"|"retarget">{
 private readonly token:string;private readonly timeoutMs:number;private readonly fetcher:Fetcher;
 constructor(token:string,timeoutMs:number,fetcher:Fetcher=globalThis.fetch){if(!token||!Number.isSafeInteger(timeoutMs)||timeoutMs<=0||typeof fetcher!=="function")throw new BitbucketProviderError("invalid_request","Bitbucket mutation token, finite timeout, and fetch are required.");this.token=token;this.timeoutMs=timeoutMs;this.fetcher=fetcher;}
 private async request(repositoryId:string,pullRequestNumber:number,method:"POST"|"PUT",suffix:string,body:unknown){if(!Number.isSafeInteger(pullRequestNumber)||pullRequestNumber<=0)throw new BitbucketProviderError("invalid_request","Positive pull request number is required.");const {workspace,repo}=parts(repositoryId);let response:Response;try{response=await this.fetcher(`https://api.bitbucket.org/2.0/repositories/${workspace}/${repo}/pullrequests/${pullRequestNumber}${suffix}`,{method,headers:{accept:"application/json",authorization:`Bearer ${this.token}`,"content-type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(this.timeoutMs),redirect:"error"});}catch(error){throw new BitbucketProviderError("provider_unavailable","Bitbucket mutation request failed without retry.",{cause:error});}if(!response.ok)throw new BitbucketProviderError("provider_unavailable",`Bitbucket mutation returned HTTP ${response.status}.`);try{return record(await response.json(),"Bitbucket mutation response");}catch(error){if(error instanceof BitbucketProviderError)throw error;throw new BitbucketProviderError("incomplete_evidence","Bitbucket mutation response was not valid JSON.",{cause:error});}}
 async merge(input:{repositoryId:string;pullRequestNumber:number;expectedHeadSha:string}){const result=await this.request(input.repositoryId,input.pullRequestNumber,"POST","/merge",{type:"pullrequest",close_source_branch:false,merge_strategy:"merge_commit"});const source=text(nested(result,"source","commit"),"hash");if(source!==input.expectedHeadSha)throw new BitbucketProviderError("incomplete_evidence","Merged pull request head does not match expected head.");const state=text(result,"state");const sha=text(nested(result,"merge_commit"),"hash");return{merged:state==="MERGED",sha};}
 async retarget(input:{repositoryId:string;pullRequestNumber:number;newBaseRef:string;expectedHeadSha:string}){const result=await this.request(input.repositoryId,input.pullRequestNumber,"PUT","",{destination:{branch:{name:input.newBaseRef}}});const head=text(nested(result,"source","commit"),"hash");const base=text(nested(result,"destination","branch"),"name");if(head!==input.expectedHeadSha||base!==input.newBaseRef)throw new BitbucketProviderError("incomplete_evidence","Bitbucket retarget was not confirmed.");}
}
export interface BitbucketMergeDependencies {readonly client:Pick<GitHubMutationClient,"merge"|"retarget">;rebase(input:{repositoryId:string;pullRequestNumber:number;expectedHeadSha:string}):Promise<{headSha:string}>;consume(input:SensitiveActionConsumption):Promise<void>;verify(input:{repositoryId:string;pullRequestNumber:number;headSha:string;baseRef:string;invalidatedReceiptHash:string}):Promise<{verificationId:string;completedAt:string}>;}
export function executeBitbucketMerge(input:ProviderMergeRequest,deps:BitbucketMergeDependencies):Promise<ProviderMergeResult>{return executeProviderMerge(input,{client:{merge:value=>deps.client.merge(value),retarget:value=>deps.client.retarget(value),rebase:value=>deps.rebase(value)},consume:value=>deps.consume(value),verify:value=>deps.verify(value)});}
