import assert from "node:assert/strict";
import test from "node:test";
import { executeGitHubMerge, type MergeDependencies } from "./providers.github-mutation.ts";
const A="a".repeat(40),B="b".repeat(40),C="c".repeat(40),M="m".repeat(40);
const claim={repositoryId:"acme/repo",pullRequestNumber:10,branch:"feature",headSha:A,baseRef:"main",observedAt:"2026-07-15T16:00:00Z",maxAgeMs:60_000,local:{commitSha:A,branch:"feature",pushed:true,verificationId:"v1",verificationCompletedAt:"2026-07-15T15:59:00Z"}};
const evidence={provider:"github" as const,repositoryId:"acme/repo",pullRequestNumber:10,state:"open" as const,merged:false,updatedAt:"2026-07-15T15:59:00Z",observedAt:"2026-07-15T15:59:30Z",headRef:"feature",headSha:A,headRepositoryId:"acme/repo",baseRef:"main",baseRepositoryId:"acme/repo",ciState:"success" as const,reviewState:"approved" as const};
const auth={schemaVersion:1 as const,policyVersion:1 as const,authorizationId:"auth-1",actor:{actorId:"human-1",authenticatedPrincipalId:"principal-1",channel:"pi_tui" as const},resource:{type:"pull_request" as const,repositoryId:"acme/repo",resourceId:"10",immutableTarget:A},operation:"merge" as const,riskClass:"security" as const,issuedAt:"2026-07-15T15:58:00Z",expiresAt:"2026-07-15T16:05:00Z",rationale:"approved",auditEventId:"audit-1",oneUseNonce:"nonce-1"};
function deps(log:any[]=[]):MergeDependencies{return{client:{merge:async input=>{log.push(["merge",input]);return{merged:true,sha:M}},retarget:async input=>{log.push(["retarget",input])},rebase:async input=>{log.push(["rebase",input]);return{headSha:C}}},consume:async input=>{log.push(["consume",input])},verify:async input=>{log.push(["verify",input]);return{verificationId:"v2",completedAt:"2026-07-15T16:01:00Z"}}};}
const base={claim,evidence,now:claim.observedAt,descendants:[]};
test("low-risk merge performs exact descendant maintenance and verification",async()=>{const log:any[]=[];const result=await executeGitHubMerge({...base,descendants:[{pullRequestNumber:11,headSha:B,baseRef:"feature",receiptHash:"old"}]},deps(log));assert.deepEqual(log,[["merge",{repositoryId:"acme/repo",pullRequestNumber:10,expectedHeadSha:A}],["retarget",{repositoryId:"acme/repo",pullRequestNumber:11,newBaseRef:"main",expectedHeadSha:B}],["rebase",{repositoryId:"acme/repo",pullRequestNumber:11,expectedHeadSha:B}],["verify",{repositoryId:"acme/repo",pullRequestNumber:11,headSha:C,baseRef:"main",invalidatedReceiptHash:"old"}]]);assert.deepEqual(result,{mergeSha:M,receiptHash:result.receiptHash,descendants:[{pullRequestNumber:11,oldHeadSha:B,newHeadSha:C,newBaseRef:"main",invalidatedReceiptHash:"old",verificationId:"v2"}]});assert.match(result.receiptHash,/^[a-f0-9]{64}$/);});
test("high-risk consumes exact authorization before merge",async()=>{const log:any[]=[];await executeGitHubMerge({...base,riskClass:"security",authorization:auth,consumedAuthorizationIds:[],consumedNonces:[]},deps(log));assert.equal(log[0][0],"consume");assert.deepEqual(log[0][1],{authorizationId:"auth-1",oneUseNonce:"nonce-1",actorId:"human-1",auditEventId:"audit-1",resource:auth.resource,operation:"merge",consumedAt:claim.observedAt});assert.equal(log[1][0],"merge");});
for(const [name,patch,code] of [["stale head",{evidence:{...evidence,headSha:C}},"claim_mismatch"],["failed CI",{evidence:{...evidence,ciState:"failure"}},"ci_not_successful"],["stale review",{evidence:{...evidence,reviewState:"pending"}},"review_not_approved"]] as const)test(`${name} rejects`,async()=>assert.rejects(()=>executeGitHubMerge({...base,...patch} as any,deps()),(e:any)=>e.code===code));
test("strict merge request shape rejects advisory and malformed descendants",async()=>{for(const value of [null,{...base,scopeFacts:[]},{...base,descendants:{}},{...base,descendants:[{pullRequestNumber:11,headSha:B,baseRef:"feature",receiptHash:"x"},{pullRequestNumber:11,headSha:C,baseRef:"feature",receiptHash:"y"}]},...([0,"",null] as const).map(v=>({...base,descendants:[{pullRequestNumber:v,headSha:B,baseRef:"feature",receiptHash:"x"}]})),...(["headSha","baseRef","receiptHash"] as const).map(k=>({...base,descendants:[{pullRequestNumber:11,headSha:B,baseRef:"feature",receiptHash:"x",[k]:""}]}))])await assert.rejects(()=>executeGitHubMerge(value as any,deps()),/merge_request_invalid/);});
test("low-risk rejects authorization-shaped inputs",async()=>{for(const patch of [{authorization:auth},{consumedAuthorizationIds:[]},{consumedNonces:[]}])await assert.rejects(()=>executeGitHubMerge({...base,...patch} as any,deps()),/merge_request_invalid/);});
test("high-risk requires every authorization input and rejects mismatch/replay",async()=>{for(const patch of [{},{authorization:auth},{authorization:auth,consumedAuthorizationIds:[]},{authorization:{...auth,resource:{...auth.resource,immutableTarget:C}},consumedAuthorizationIds:[],consumedNonces:[]},{authorization:auth,consumedAuthorizationIds:["auth-1"],consumedNonces:[]}])await assert.rejects(()=>executeGitHubMerge({...base,riskClass:"security",...patch} as any,deps()));});
test("descendants must be immediate and distinct",async()=>{for(const d of [{pullRequestNumber:11,headSha:B,baseRef:"other",receiptHash:"x"},{pullRequestNumber:10,headSha:B,baseRef:"feature",receiptHash:"x"}])await assert.rejects(()=>executeGitHubMerge({...base,descendants:[d]},deps()),/descendant_mismatch/);});
test("unconfirmed merge rejects",async()=>{for(const result of [{merged:false,sha:M},{merged:true,sha:""}]){const d=deps();d.client.merge=async()=>result as any;await assert.rejects(()=>executeGitHubMerge(base,d),/merge_not_confirmed/);}});
test("rebase and verification must be confirmed",async()=>{for(const mode of ["empty","same","verify-id","verify-time"]){const d=deps();if(mode==="empty")d.client.rebase=async()=>({headSha:""});if(mode==="same")d.client.rebase=async()=>({headSha:B});if(mode==="verify-id")d.verify=async()=>({verificationId:"",completedAt:claim.observedAt});if(mode==="verify-time")d.verify=async()=>({verificationId:"v",completedAt:"bad"});await assert.rejects(()=>executeGitHubMerge({...base,descendants:[{pullRequestNumber:11,headSha:B,baseRef:"feature",receiptHash:"x"}]},d),/descendant_(rebase_not_confirmed|verification_invalid)/);}});
test("provider failure is visible and does not continue",async()=>{const log:any[]=[];const d=deps(log);d.client.rebase=async()=>{log.push(["rebase"]);throw new Error("conflict")};await assert.rejects(()=>executeGitHubMerge({...base,descendants:[{pullRequestNumber:11,headSha:B,baseRef:"feature",receiptHash:"x"}]},d),/conflict/);assert.deepEqual(log.map(x=>x[0]),["merge","retarget","rebase"]);});
